apiVersion: v1
kind: Service
metadata:
  name: yuantalife-cms-ui
  namespace: yuanta  
  labels:
    app: yuantalife-cms-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100
  selector:
   app: yuantalife-cms-ui